# Site settings
title: Ryan Ranch Vaccine
author: Michael Airola
description: >- # this means to ignore newlines until "baseurl:"
  Need a vaccine in the Monterey area? Schedule an apointment at Ryan Ranch and download all necessary paperwork
  here!
keywords:
  vaccine, vaccines, vaccination, vaccinations, ryan ranch
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://localhost.com:4000"
url: "https://ryanranchvaccine.com"

# Home intro
# intro-line-1: Need a vaccine? Schedule an apointment and download all necessary paperwork here!
intro-line-1: Need a vaccine in the Monterey area? 
intro-line-2: Schedule an apointment and download all necessary paperwork here!

# Contact button
button-label: Schedule Vaccination
button-link: https://michaelairola.com

# Projects
projects:
  # - name: 
  - name: Download Paperwork
    description: Download the necessary paperwork for a quick and easy appointment
    image: ximenacalle.png
    link: http://ximenacalle.com

# Social
socialmedia:

  - name: Facebook
    link: https://www.facebook.com/pandamints

  - name: Twitter
    link: https://twitter.com/wearepandamints

  - name: Instagram
    link: https://www.instagram.com/upscalemints/

# Google Analytics
# gaid: UA-109520023-1

# Build settings
plugins:
  - jekyll-feed