# Site Settings
title: Ryan Ranch Vaccines
author: Michael Airola
# description: >-
#   Need a vaccine for COVID-19 in the Monterey area? Schedule an apointment at Ryan Ranch and download all necessary paperwork
#   here!
description: >-
  Now vaccinating healthcare providers and individuals age 75 and older. 
  Want to b alerted when vaccine appointments become available? 
  Fill out the interest form below.
whois: >-
  Ryan Ranch Vaccine Clinic is run by Monterey Peninsula Pediatric Medical Group. 
  As a COVID-19 Vaccination Program, we administer Pfizer and Moderna Vaccines distributed by Monterey County Health Department.
keywords:
  vaccine, vaccines, vaccination, vaccinations, ryan ranch

active: false

# Home intros
intro-1: Now vaccinating healthcare providers and individuals age 75 and older.
intro-2: Want to be alerted when vaccine appointments become available? Fill out the interest form below.

intro-active-1: Need a vaccine for COVID-19 in the Monterey area? 
intro-active-2: Schedule an apointment and download all necessary paperwork here!

# Contact buttons
button-label: Join waiting list for vaccines
button-link: https://docs.google.com/forms/d/e/1FAIpQLSfXVdPIK9rYKhnuIF_fGkr_GHPX4q_8qtWk4PB0yytWBV3L_w/viewform

active-button-label: Schedule Vaccination
active-button-link: https://www.appointmentplus.com/solutions/medical-scheduling-software/

# Projects
projects:
  # - name: Download Paperwork
  #   description: Download the necessary paperwork for a quick and easy appointment
  #   image: paperwork.png
  #   link: /assets/images/paperwork.pdf
  #   type: download
  - name: CDC information on COVID-19
    description: Click here to review what the CDC has to say about the COVID-19 virus and vaccines for it
    image: cdc.png
    link: https://www.cdc.gov/coronavirus/2019-ncov/vaccines/expect.html
    type: link
about:
  - name: Our Location
    image: location.jpeg
    lines: 
      - 2 Upper Ragsdale Dr suite b-210, Monterey, CA 93940

  - name: Other Info 
    image: about.jpeg
    lines: 
      - "Phone: 831-333-0999"
      - "Fax: 831-333-0909"
      - "Mail: ryanranchvaccines@gmail.com"

# Social
socialmedia:
  
  - name: Facebook
    link: https://www.facebook.com/pediatricians?ref=ts

  - name: Email
    link: mailto:ryanranchvaccines@gmail.com

#   - name: Twitter
#     link: https://twitter.com/

#   - name: Instagram
#     link: https://www.instagram.com/

# Google Analytics
# gaid: UA-109520023-1
gaid: G-CMBSQKVY1K
# Build settings
plugins:
  - jekyll-feed