steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ryan-ranch-vaccinations', '-f', '_build/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ryan-ranch-vaccinations']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'resume', '--image', 'gcr.io/ryan-ranch-vaccinations', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
