steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ryan-ranch-vaccinations/master', '-f', '_build/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ryan-ranch-vaccinations/master']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'ryan-ranch-vaccinations', '--image', 'gcr.io/ryan-ranch-vaccinations/master', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
